version: "3.8"

services:
  iot-app:
    image: iot-app:latest
    container_name: iot-app
    restart: unless-stopped
    env_file:
      - path: sample.env
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_PORT=${APP_PORT}
      - APP_REDIS_SERVER=${APP_REDIS_SERVER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      # Optional
      #- ULTRALYTICS_VERSION=8.3.6
      #- BENCHED=True
      #- SECRET_KEY=${SECRET_KEY}
      #- ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # Add the following lines to enable OIDC
      #- USE_OIDC=${USE_OIDC}
      #- OIDC_HOST=${OIDC_HOST}
      #- OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      #- OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      #- OIDC_REALM_NAME=${OIDC_REALM_NAME}
      #- OIDC_CERT_URL=${OIDC_CERT_URL}
      #- OIDC_TOKEN_URL=${OIDC_TOKEN_URL}
      #- OIDC_AUTH_URI=${OIDC_AUTH_URI}
      #- OIDC_TOKEN_URI=${OIDC_TOKEN_URI}
      #- OIDC_ISSUER=${OIDC_ISSUER}
      #- OIDC_REDIRECT_URI=${OIDC_REDIRECT_URI}
      #- OIDC_SCOPES=${OIDC_SCOPES}
      #- OIDC_USERINFO_URI=${OIDC_USERINFO_URI}
      #- OIDC_TOKEN_INTROSPECTION_URI=${OIDC_TOKEN_INTROSPECTION_URI}
      #- OIDC_SERVER_METADATA_URL=${OIDC_SERVER_METADATA_URL}
      #- OIDC_ALLOWED_ROLES=${OIDC_ALLOWED_ROLES}
      #- OIDC_SCOPES=${OIDC_SCOPES}
    privileged: true
    volumes:
      - /run/udev:/run/udev:ro
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - monitoring
    ports:
      - "${APP_PORT}:${APP_PORT}"
    ## Uncomment the following lines to deploy the service on a GPU-enabled node
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  monitoring:
    driver: bridge
