#!/bin/bash

#set -o errexit
#set -o pipefail
#set -o nounset


# server.pid datei löschen falls existiert
if [ -f "server.pid" ]; then
  rm -f "server.pid"
fi

# Setzen des SECRET_KEY, falls nicht vorhanden
: "${SECRET_KEY:=$(openssl rand -base64 32)}"
export SECRET_KEY
#echo "SECRET_KEY gesetzt: ${SECRET_KEY}"

# Setzen des ENCRYPTION_KEY, falls nicht vorhanden
: "${ENCRYPTION_KEY:=$(openssl rand -base64 32)}"
export ENCRYPTION_KEY
#echo "ENCRYPTION_KEY gesetzt: ${ENCRYPTION_KEY}"


# Aktiviere die virtuelle Umgebung
source /venv/bin/activate

/restart_server &

# Führt den angegebenen Befehl aus (hier python3 app.py)
exec "$@"