#!/bin/bash

RESTART_FILE="restart.flag"

mkdir -p data/logs

LOG_FILE="data/logs/SYSTEM_RESTART.log"

touch $LOG_FILE

while true; do
    if [ -f "server.pid" ]; then
        SERVER_PID=$(cat server.pid)

        # Prüfe, ob die RESTART_FILE existiert
        if [ -f "$RESTART_FILE" ]; then
            echo "Server-Neustart erkannt." >> $LOG_FILE
            rm -f "$RESTART_FILE"

            # Sende SIGTERM an den Server-Prozess und warte auf die Beendigung
            kill -15 $SERVER_PID
            echo "SIGTERM an Server gesendet (PID: $SERVER_PID)." >> $LOG_FILE
            sleep 5

            # Falls der Prozess noch läuft, sende SIGKILL als letzten Ausweg
            if ps -p $SERVER_PID > /dev/null; then
                echo "Prozess wurde nicht beendet. Erzwinge Shutdown." >> $LOG_FILE
                kill -9 $SERVER_PID
            fi

            echo "Server wird neu gestartet..." >> $LOG_FILE
            python app.py
            NEW_SERVER_PID=$!
            echo $NEW_SERVER_PID > server.pid
            echo "Server neu gestartet mit PID: $NEW_SERVER_PID." >> $LOG_FILE
        fi
    fi

    sleep 2
done
